title: Sumit Kar
subtitle: Software Engineer at Cisco Systems (India)
description: >- # this means to ignore newlines until "baseurl:"
  'Technology Enthusiast | Photographer | Foodie | Numismatist'

url: "https://www.sumitkar.in" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog
fb_app_id: "513486439531583"
urls:
    - text: About Me
      url: /about
    - text: Blog
      url: https://blog.sumitkar.in/
    - text: Contact Me
      url : /contact

author_logo: sumit-kar.jpeg
author: Sumit Kar
author_bio: 

author_education_details:
              - college_logo: 
                college_name: 
                college_url: https://www.nmims.edu
                college_degree: Information Technology and System Management
                description: PGDM
                visibility: true
              - college_logo: 
                college_name: Swami Vivekananda Institute of Science and Technology
                college_url: https://svist.org
                college_degree: Computer Science Engineer
                description: Bachelor of Technology
                visibility: true
              - college_logo: 
                college_name: A. K. Ghosh Memorial School
                college_url: http://akgms.edu.in
                college_degree: Science
                description: High School
                visibility: true

author_skill_strong:
          - tech_name: Java
            tech_logo: java.png
            visibility: true
          - tech_name: Apache Tomcat
            tech_logo: tomcat.png
            visibility: true
          - tech_name: Docker
            tech_logo: docker.png
            visibility: true
          - tech_name: SQL
            tech_logo: sql.png
            visibility: true
          - tech_name: HTML5
            tech_logo: html5-logo.png
            visibility: true
          - tech_name: CSS3
            tech_logo: css3-logo.png
            visibility: true
          - tech_name: JavaScript
            tech_logo: javascript-logo.png
            visibility: true
          - tech_name: jQuery
            tech_logo: jquery-logo.png
            visibility: true
          - tech_name: Angular
            tech_logo: angular.png
            visibility: true
          - tech_name: Bootstrap
            tech_logo: bootstrap-logo.png
            visibility: true
          - tech_name: Wordpress
            tech_logo: wordpress-logo.png
            visibility: true
          - tech_name: Drupal
            tech_logo: drupal-logo.png
            visibility: true
          - tech_name: Photoshop
            tech_logo: photoshop-logo.png
            visibility: true
          - tech_name: GIMP
            tech_logo: gimp.png
            visibility: true
          - tech_name: Office Utilities
            tech_logo: office-logo.png
            visibility: true
          - tech_name: Git
            tech_logo: github-logo.png
            visibility: true
          - tech_name: Ubuntu
            tech_logo: ubuntu.png
            visibility: true
          - tech_name: CentOS
            tech_logo: centos_logo.jpg
            visibility: true
          - tech_name: Android
            tech_logo: android-logo.png
            visibility: true
          - tech_name: PHP
            tech_logo: php-logo.png
            visibility: true
          - tech_name: C / C++
            tech_logo: cpp-logo.png
            visibility: true
          - tech_name: ELK
            tech_logo: elk.png
            visibility: true
          - tech_name: Jenkins
            tech_logo: jenkins.png
            visibility: true
          
          



# social links
twitter_username: TimusRak
github_username:  karsumit94
facebook_username: www.sumitkar.in  
linkedin_username: timusrak
instagram_username: sumitkar.in


#for comments using disqus
disqus_shortname: timusrak94

# formspree (contact form)
formspree_email: karsumit94@live.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class   : 'syntax'
permalink: pretty

# google analytics
google_analytics: UA-102170653-1

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true
show_author_skill_strong: true 
show_author_skill_basics: true 

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings

# theme: timus

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Ads.txt

destination: ./build
